mysql -uroot<<EOF
CREATE USER "$MYSQL_ADMIN"@"$DOMAIN" IDENTIFIED BY "$MYSQL_ADMIN_PASSWORD";
CREATE DATABASE auth;
GRANT ALL PRIVILEGES ON auth.* TO "$MYSQL_ADMIN"@"$DOMAIN";
USE auth;
CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);
INSERT INTO user (email, password) VALUES ("$MYSQL_EMAIL", "$MYSQL_PASSWORD");
EOF
