apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: sql
      protocol: TCP
      port: 3306
      targetPort: 3306
