mysql <<EOF
CREATE USER "{$MYSQL_ADMIN}"@"locahost" IDENTIFIED BY "{$MYSQL_ADMIN_PASSWORD}";
CREATE DATABASE auth;
GRANT ALL PPRIVILEGES ON auth.* TO "{$MYSQL_ADMIN}"@"locahost";
USE auth;
CREATE TABLE user (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);
INSERT INTO user (email, password) VALUES ("{$MYSQL_USER}", "{$MYSQL_PASSWORD}");
EOF